name: Build Static Project

on:
  push:
    branches:
      - main  # Cambia esto según tu rama principal
  pull_request:
    branches:
      - main  # Cambia esto según tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
